### ISSUE TITLE
Tasks or/and Use Cases?

### ISSUE THREAD

**Issue by ArturTan** [Liquid-Legal-Institute/Legal-Text-Analytics#12]
I would like to propose rewording Selected Use Cases to Selected NLP Tasks or to differentiate items between two categories.

In the NLP community, a "task" is some scientific-linguistic problem. See [1](https://www.kdnuggets.com/2018/10/main-approaches-natural-language-processing-tasks.html)

A "use case" has a business connotation, and its rationale is about "utilization". 

For example, named entity recognition is an NLP task. 

But, anonymization is a business (and legal) use case, resulted from GDPR/privacy law constraints, and can be solved by a Named Entity Recognition solution.

**Comment by bwaltl** [comment]
Great observation and remark. There is no 100% clear distinction intersection between task and use case in the context of NLP and the legal domain. NER could already be a use case in the legal domain, e.g. in the context of the analysis of contracts. 

Should we consider renaming the Section from "Use Cases" to "Tasks and Use Cases". I would intentionally avoid "Downstream Tasks" as this covers only a portion of what is available in the lists.
